services:
  db:
  image: postgress:latest
  restart: unless-stopped
  ports:
     -${WSRS_DATABASE_PORT:-5432}:5432
  environment:  
     POSTGRES_USER: ${WSRS_DATABASE_USER}
     POSRGRESS_PASSWORD: ${WSRS_DATABASE_PASSWORD}
     POSTGRESS_DB: ${WSRS_DATABASE_NAME}
  volumes:
    -db:/var/lib/postgressql/data
  
  pgadmin:
   image: dpage/pgadmin4:latest~
   restart: unless-stopped
   depends_on:
     - db
   ports:
   - 8081:80
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: password
  volumes:



volumes:
  db:
    driver: local
  pgadmin
  driver: local
    .yml[+]